use std::collections::HashMap;
use std::env;

// This macro builds a registry of solutions from a file generated at compile-time.
macro_rules! aoc_registry {
    ($(($year:expr, $day:expr, $path:expr)),* $(,)?) => {{
        let mut map: HashMap<String, fn()> = HashMap::new();
        $(
            map.insert(
                format!("{}_day{:02}", $year, $day),
                {
                    // Each module must have a `run()` function
                    #[path = $path]
                    mod tmp;
                    fn wrapper() {
                        if let Err(e) = tmp::run() {
                            eprintln!("Error running {}_day{:02}: {}", $year, $day, e);
                        }
                    }
                    wrapper
                }
            );
        )*
        map
    }};
}

// This file is autogenerated by build.rs — described below.
include!("aoc_index.rs");

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        eprintln!("Usage: cargo run -- <year_day>  (e.g., 2024_day01)");
        return;
    }

    let key = args[1].to_lowercase();
    let registry = aoc_registry();

    match registry.get(&key) {
        Some(func) => func(),
        None => eprintln!("Unknown problem: {key}. Available keys: {:?}", registry.keys()),
    }
}
